### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pvalincius** [heyqule/enemy_race_manager#3]
The mod Enemy Race Manager (1.9.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event enemyracemanager::on_nth_tick(61)
__enemyracemanager__/lib/attack_group_chunk_processor.lua:363: attempt to index local 'surface_data' (a nil value)
stack traceback:
	__enemyracemanager__/lib/attack_group_chunk_processor.lua:363: in function 'find_attack_position'
	__enemyracemanager__/lib/attack_group_chunk_processor.lua:507: in function 'pick_attack_location'
	__enemyracemanager__/lib/attack_group_processor.lua:134: in function 'add_to_group'
	__enemyracemanager__/lib/attack_group_processor.lua:244: in function 'add_to_group_cron'
	__enemyracemanager__/control.lua:51: in function '?'
	__enemyracemanager__/lib/cron_processor.lua:23: in function 'process_cron'
	__enemyracemanager__/lib/cron_processor.lua:76: in function 'process_1_sec_queue'
	__enemyracemanager__/control.lua:339: in function 'handler'
	__stdlib__/stdlib/event/event.lua:342: in function 'pcall'
	__stdlib__/stdlib/event/event.lua:362: in function 'dispatch_event'
	__stdlib__/stdlib/event/event.lua:438: in function <__stdlib__/stdlib/event/event.lua:396>

**Comment by heyqule** [comment]
May you send me your save?

**Comment by heyqule** [comment]
1.9.3 from mod portal should fix the issue.  Please let me know if the crash still there.

**Comment by pvalincius** [comment]
Hi,

Crash does not occur again.

Thx.

2021-11-07, sk, 17:48 heyqule ***@***.***> rašė:

**Comment by pvalincius** [comment]
Hi, I'm getting a new issue.

The mod Enemy Race Manager (1.12.0) caused a non-recoverable error.

Error while running event enemyracemanager::on_ai_command_completed (ID 117)
LuaUnitGroup API call when LuaUnitGroup was invalid.
stack traceback:
[C]: in function '__index'
__enemyracemanager__/control.lua:121: in function
'ermGroupCacheTableCleanup'
__enemyracemanager__/control.lua:155: in function 'handler'
__stdlib__/stdlib/event/event.lua:342: in function 'pcall'
__stdlib__/stdlib/event/event.lua:362: in function 'dispatch_event'
__stdlib__/stdlib/event/event.lua:438: in function
<__stdlib__/stdlib/event/event.lua:396>

2021-11-07, sk, 18:13 Paulius Valincius ***@***.***> rašė:

**Comment by heyqule** [comment]
@pvalincius May you send me your save?

**Comment by pvalincius** [comment]
Save failas

https://drive.google.com/file/d/1tMfSszjfIPoGTqs6O9L4PWhkeWxnLYT2/view?usp=sharing

**Comment by heyqule** [comment]
@pvalincius 1.12.1 fixed it

**Comment by pvalincius** [comment]
Thx
