### ISSUE TITLE
Reinforced pipes available from begining

### ISSUE THREAD

**Issue by OndrejMus** [heyqule/enemy_race_manager#32]
Hi, it might be good to disable recipes for reinforced pipes and reinforced pipes to ground by default and unlock after materials are unlocked.

New map, only mod is ERM:
![image](https://user-images.githubusercontent.com/77000568/213021375-890434c8-d375-4a17-9b7d-90faa68fcb8e.png)

**Comment by heyqule** [comment]
ya. reinforced version of the items are automatically unlocked when the regular version researched.  Pipes don't need to research hence it's "available" from beginning.  I don't want to create another set of technologies to unlock the reinforced items.

I could hide the pipes behind low density structure research.  But it doesn't really matter IMO.

**Comment by OndrejMus** [comment]
Ok, I was just confused for a little while while I was looking at it and realized I'm not able to craft them because I don't have LDS researched and thought you might want to know :)
