### ISSUE TITLE
Space Age Compatibility Issues when SA is Disabled

### ISSUE THREAD

**Issue by Akrotluv** [heyqule/enemy_race_manager#52]
Long story short, I've been getting these other issues that directly relate to owning but having Space Age disabled.
![image](https://github.com/user-attachments/assets/72650d9c-6a23-4772-a4d7-540c7d2ad938)
![image](https://github.com/user-attachments/assets/1dc4449d-7594-4949-9f56-84fd0dee3c0b)
![image](https://github.com/user-attachments/assets/1c023584-78b1-4ad8-922a-a06701047e78)

**Comment by heyqule** [comment]
lol. forgot to do a test run on non space-age game.

**Comment by heyqule** [comment]
I don't see those on my end.  Do you have any mod that enable feature_flags without having those space-age enabled?

**Comment by heyqule** [comment]
like this one.. https://mods.factorio.com/mod/enable-all-feature-flag

**Comment by heyqule** [comment]
It's on them to fix.  They misused the feature_flags.
